DATA:
  IMAGE_SIZE: 256
  IN_CHANS: 1
  NUM_CLASSES: 4
  MEAN: 0.28328466976390165
  STD: 0.12623453327253753
MODEL:
  ENCODER:
    USE_MULTI_MERGE: True
    USE_GHOST_FFN: True
    USE_IRFFN: False
    USE_LPU: False
  DECODER:
    EMBED_DIM: 24
    FUSE_OP: 'cat'
TRAIN:
  EPOCHS: 50
  WARMUP_EPOCHS: 0
  LR: 6e-5
  
